version: '3'

volumes:
  ikev2-vpn-data:

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    environment:
      - 'VPN_IPSEC_PSK=${VPN_IPSEC_PSK}'
      - 'VPN_USER:${VPN_USER}'
      - 'VPN_PASSWORD:${VPN_PASSWORD}'
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
